---
title: "Track I: Report and publish"
format: html
---

# Instructions

For this final milestone, showcase your project by creating a Quarto report in one of the following formats:

* HTML report: https://quarto.org/docs/output-formats/html-basics (possibly with parameters: https://quarto.org/docs/computations/parameters.html)
* Slideshow: https://quarto.org/docs/presentations/revealjs/
* Dashboard: https://quarto.org/docs/dashboards/

Your report should bring together code from previous milestones (add new code if you wish) to tell a coherent story of either:

a) the project data (via your project-based extensions) or 
b) your own data (if you have worked with your own data in extensions)

When you're done, publish your report to Posit Connect Cloud to share with your teammates. The **Publish to Posit Connect Cloud** tutorial on your course site walks you through it, including how to get a public link to share. See here for an overview of publishing to Connect Cloud: https://docs.posit.co/connect-cloud/

As you work on this milestone, you may want to refer to the following pages from the Quarto docs:

* Markdown Basics: https://quarto.org/docs/authoring/markdown-basics.html
* HTML Basics: https://quarto.org/docs/output-formats/html-basics.html
* Execution Options: https://quarto.org/docs/computations/execution-options.html
* Quarto Cheatsheet: https://rstudio.github.io/cheatsheets/quarto.pdf

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('display.max_columns', None)
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off
```


## Report and publish

(Create your Quarto report here, or start a new Quarto document.)
