---
title: "Write functions"
format: html
---
# Instructions

This week, you learned how to write and apply your own functions. 

You'll use these skills to add a columns that recodes stock index symbol into their full names. 

To learn more about the variables contained in the data set, refer to the data dictionary [here](https://rstudio.github.io/academy-python-stock-portfolios/assets/indexes_dictionary.html).

# Milestone

```{python}
#| label: 'setup'
#| include: false

# Import your packages here
import pandas as pd
from matplotlib import rcParams

# Set some options
pd.set_option('mode.copy_on_write', True) # Enables copy on write
pd.set_option('display.max_columns', None) # Set a display option so all columns of tables are displayed
rcParams.update({'savefig.bbox': 'tight'}) # Keeps plotnine legend from being cut off

```

## Write functions

As we work towards building polished reports and plots, it may be useful to include the full name of stock indexes within our data set rather than the symbol. In this milestone, you'll create a new variable that contains the full names associated with each stock index symbol.

## Recreation

### Part 1 - Import

Before you begin, you will need to import your data set. Use the code chunk below to read the data from the data file `indexes.csv`, which is stored in the `data/` folder in your working directory. Be sure to save the data set to a variable named `indexes`.

```{python}
#| label: 'recreation_import'
```

### Part 2 - Write a function


Your task is to write a function named `recode_symbol()` that will accept a single string value as input (e.g. `'^GSPC'`) 
and return the associated name:

- '^DJI':  'Dow Jones'
- '^FVX':  '5 Year Treasury'
- '^GSPC': 'S&P 500'
- '^IRX':  '13 Week Treasury'
- '^IXIC': 'NASDAQ'
- '^TNX':  '10 Year Treasury'


```{python}
#| label: 'recreation-function'


```

#### Check your work 

Run the following code chunk to test your function on a few different values:

```{python}
#| label: 'compare_results'

recode_symbol('^TNX') # should return `10 Year Treasury`
recode_symbol('^GSPC') # should return `S&P 500`
recode_symbol('^DJI') # should return `Dow Jones`

```

### Part 3 - Apply

Using your function, add a new column to `indexes` called `name` that contains the name associated with each symbol. 

```{python}
#| label: 'recreation_apply'

```

## Extension

Use the code chunk(s) below to extend your work. Try something that you can learn from experimentation, a help page or a package website. Consider:

1. Writing a function to perform a calculation involving one or more columns of `indexes`
2. Writing a function that subsets the data set for a given symbol value and creates a visualization
3. Something else

```{python}
#| label: 'extension'

```

